name: Auto Update GitBook SUMMARY.md

on:
  push:
    paths:
      - 'pages/**'
    branches:
      - main

jobs:
  update-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate SUMMARY.md
        run: |
          echo "# Summary" > SUMMARY.md
          find pages -type f -name '*.md' | sort | while read file; do
            title=$(head -n 1 "$file" | sed 's/# //')
            path=$(echo "$file" | sed 's|pages/||')
            echo "* [$title](pages/$path)" >> SUMMARY.md
          done

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add SUMMARY.md
          git diff --cached --quiet || git commit -m "Auto-update SUMMARY.md"
          git push
          
