name: GitBook Auto Build & Summary Update

on:
  push:
    branches:
      - main   # change if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed to push changes

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install GitBook CLI
        run: npm install -g gitbook-cli

      - name: Build GitBook in pages/
        working-directory: pages
        run: gitbook build

      - name: Check for SUMMARY.md changes
        id: diff
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet SUMMARY.md || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes if any
        if: steps.diff.outputs.changed == 'true'
        run: |
          git add pages/SUMMARY.md
          git commit -m "Auto update SUMMARY.md via GitHub Actions"
          git push origin main
