name: Auto Update GitBook

on:
  push:
    branches: [main]

jobs:
  update-gitbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitBook SUMMARY.md
        run: |
         echo "# Table of Contents " > SUMMARY.md
          find pages -type f -name "*.md" | sort | while read file; do
            title=$(head -1 "$file" | sed 's/^# //')
            relpath="${file}"
            echo "* [${title}](${relpath})" >> SUMMARY.md
          done

      - name: Commit & Push if changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add SUMMARY.md
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update SUMMARY.md"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
